"""
IBVAP Incident Management Layer
Orchestrates conversion of confirmed SpatialEvents into persistent forensic incidents,
annotated image snapshots, and indexed SQLite records.
Decoupled from video ingestion and frontend UI.
"""

from datetime import datetime, timezone
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Tuple, Union

import cv2
import numpy as np
import yaml

from core.spatial_engine import SpatialEvent, SpatialEventType
from core.tracker import Track
from server.database import IncidentDatabase

logger = logging.getLogger("ibvap.incident")


@dataclass
class IncidentRecord:
    """Structured security incident representation."""
    id: Optional[int]
    timestamp: float
    iso_timestamp: str
    camera_id: str
    event_type: str
    track_id: int
    object_type: str
    zone_id: str
    zone_name: str
    direction: Optional[str]
    confidence: Optional[float]
    frame_index: int
    feet_point: Tuple[float, float]
    snapshot_path: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert incident to serializable dictionary."""
        return {
            "id": self.id,
            "timestamp": self.timestamp,
            "iso_timestamp": self.iso_timestamp,
            "camera_id": self.camera_id,
            "event_type": self.event_type,
            "track_id": self.track_id,
            "object_type": self.object_type,
            "zone_id": self.zone_id,
            "zone_name": self.zone_name,
            "direction": self.direction,
            "confidence": round(self.confidence, 4) if self.confidence is not None else None,
            "frame_index": self.frame_index,
            "feet_point": [round(self.feet_point[0], 2), round(self.feet_point[1], 2)],
            "snapshot_path": self.snapshot_path,
        }


@dataclass
class IncidentConfig:
    """Configuration for incident manager and persistence."""
    camera_id: str = "CAM-01"
    db_path: str = "data/events.db"
    snapshot_dir: str = "data/snapshots"
    jpeg_quality: int = 90

    @classmethod
    def from_yaml(cls, yaml_path: Union[str, Path]) -> "IncidentConfig":
        """Load configuration from YAML file."""
        path = Path(yaml_path)
        if not path.exists():
            raise FileNotFoundError(f"Configuration file not found: {path.resolve()}")

        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        inc_cfg: Dict[str, Any] = data.get("incident", {})
        return cls(
            camera_id=str(inc_cfg.get("camera_id", "CAM-01")),
            db_path=str(inc_cfg.get("db_path", "data/events.db")),
            snapshot_dir=str(inc_cfg.get("snapshot_dir", "data/snapshots")),
            jpeg_quality=int(inc_cfg.get("jpeg_quality", 90)),
        )


class IncidentManager:
    """
    Manages security incidents generated by the spatial analytics engine:
    1. Annotates and captures forensic JPEG snapshot images.
    2. Persists structured incident records in the SQLite database.
    3. Emits validated IncidentRecord objects for upstream consumers.
    """

    def __init__(
        self,
        config: Optional[IncidentConfig] = None,
        database: Optional[IncidentDatabase] = None,
        on_incident: Optional[Callable[["IncidentRecord"], None]] = None,
    ):
        self.config = config or IncidentConfig()
        self.snapshot_dir = Path(self.config.snapshot_dir)
        self.snapshot_dir.mkdir(parents=True, exist_ok=True)

        self.db = database or IncidentDatabase(self.config.db_path)
        self.on_incident = on_incident
        self._counter = 0

    def process_event(
        self,
        event: SpatialEvent,
        frame: np.ndarray,
        track: Optional[Track] = None,
    ) -> IncidentRecord:
        """
        Process a confirmed spatial breach event:
        Saves snapshot, writes database record, and returns IncidentRecord.

        Args:
            event: SpatialEvent emitted from SpatialEngine.
            frame: Video frame array where breach occurred.
            track: Associated Track object providing bounding box and confidence.

        Returns:
            IncidentRecord with database ID and snapshot path.
        """
        self._counter += 1
        ts = event.timestamp if event.timestamp > 0 else datetime.now(timezone.utc).timestamp()
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        iso_str = dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")
        time_slug = dt.strftime("%Y-%m-%d_%H%M%S")

        # Deterministic snapshot filename:
        # e.g., 2026-09-06_192431_CAM-01_track-70_tripwire_001.jpg
        type_slug = (
            "tripwire"
            if event.event_type == SpatialEventType.TRIPWIRE_CROSSING
            else "intrusion"
        )
        safe_cam = self.config.camera_id.replace(" ", "-").replace("/", "-")
        filename = (
            f"{time_slug}_{safe_cam}_track-{event.track_id}_{type_slug}_{self._counter:03d}.jpg"
        )
        snapshot_filepath = self.snapshot_dir / filename

        # Render Forensic Snapshot
        self._render_snapshot(
            frame=frame,
            event=event,
            track=track,
            dt_str=iso_str,
            output_path=snapshot_filepath,
        )

        # Build database payload
        direction_str = event.direction.value if event.direction else None
        conf = track.confidence if track is not None else None

        db_payload = {
            "timestamp": ts,
            "iso_timestamp": iso_str,
            "camera_id": self.config.camera_id,
            "event_type": event.event_type.value,
            "track_id": event.track_id,
            "object_type": event.object_type,
            "zone_id": event.zone_id,
            "zone_name": event.zone_name,
            "direction": direction_str,
            "confidence": conf,
            "frame_index": event.frame_index,
            "feet_x": event.feet_point[0],
            "feet_y": event.feet_point[1],
            "snapshot_path": str(snapshot_filepath).replace("\\", "/"),
        }

        # Insert into SQLite
        db_record = self.db.create_incident(db_payload)

        # Construct and return IncidentRecord
        record = IncidentRecord(
            id=db_record.id,
            timestamp=ts,
            iso_timestamp=iso_str,
            camera_id=self.config.camera_id,
            event_type=event.event_type.value,
            track_id=event.track_id,
            object_type=event.object_type,
            zone_id=event.zone_id,
            zone_name=event.zone_name,
            direction=direction_str,
            confidence=conf,
            frame_index=event.frame_index,
            feet_point=event.feet_point,
            snapshot_path=str(snapshot_filepath).replace("\\", "/"),
        )

        if self.on_incident is not None:
            try:
                self.on_incident(record)
            except Exception as cb_err:
                logger.warning(f"Error in on_incident callback: {cb_err}")

        return record

    def _render_snapshot(
        self,
        frame: np.ndarray,
        event: SpatialEvent,
        track: Optional[Track],
        dt_str: str,
        output_path: Path,
    ) -> None:
        """Render forensic annotations on snapshot and write JPEG file."""
        annotated = frame.copy()
        h, w = annotated.shape[:2]

        # 1. Bounding box and feet marker for intruder
        if track is not None:
            x1, y1, x2, y2 = track.bbox.as_int_tuple()
            cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 0, 255), 3)

            # Ground feet crosshair
            fx, fy = int(track.feet_point[0]), int(track.feet_point[1])
            cv2.circle(annotated, (fx, fy), 5, (0, 255, 255), -1)
            cv2.line(annotated, (fx - 10, fy), (fx + 10, fy), (0, 255, 255), 2)
            cv2.line(annotated, (fx, fy - 10), (fx, fy + 10), (0, 255, 255), 2)

            # Label on top of box
            tag = f"INTRUDER #{track.track_id} ({track.confidence:.2f})"
            cv2.putText(
                annotated,
                tag,
                (x1, max(20, y1 - 8)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.55,
                (0, 0, 255),
                2,
                cv2.LINE_AA,
            )

        # 2. Forensic Header Banner
        cv2.rectangle(annotated, (0, 0), (w, 55), (15, 15, 15), -1)
        cv2.rectangle(annotated, (0, 0), (w, 55), (0, 0, 255), 2)

        header_line1 = (
            f"[SECURITY INCIDENT] {event.event_type.value} | "
            f"CAM: {self.config.camera_id} | TARGET: TRACK #{event.track_id}"
        )
        dir_text = f" | DIR: {event.direction.value}" if event.direction else ""
        header_line2 = (
            f"ZONE: {event.zone_name.upper()}{dir_text} | TIME: {dt_str} | FRAME: {event.frame_index}"
        )

        cv2.putText(annotated, header_line1, (20, 22), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 0, 255), 2, cv2.LINE_AA)
        cv2.putText(annotated, header_line2, (20, 44), cv2.FONT_HERSHEY_SIMPLEX, 0.48, (220, 220, 220), 1, cv2.LINE_AA)

        # 3. Write JPEG image
        params = [int(cv2.IMWRITE_JPEG_QUALITY), self.config.jpeg_quality]
        cv2.imwrite(str(output_path), annotated, params)
        logger.debug(f"Saved incident snapshot to: {output_path}")
